name: Build Gamers Lounge Website
"on":
  push:
    branches:
      - master
jobs:
  gl-build:
    name: Gamers Lounge Website Build
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    steps:
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
