name: Build Gamers Lounge Website
"on":
  push:
    branches:
      - master
jobs:
  gl-build:
    name: Gamers Lounge Website Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
