const CONTACT = 'Contact-Us'
const EVENTS = 'Events'
const GIVEAWAY = 'Giveaways'
const HOME = 'Home'
const PROFILE = 'Profile'
const STORY = 'Our-Story'
const GAME_DETAILS = 'Game-Details'
const GIVEAWAY_DETAILS = 'Giveaway-Details'
const SUMMIT_HISTORY_DETAILS = 'Summit-History-Details'
const TOURNAMENT_DETAILS = 'Tournament-Details'
const TESTIMONIALS = 'Testimonials'

export default
    [CONTACT, EVENTS, GIVEAWAY, HOME, PROFILE, STORY, GAME_DETAILS, GIVEAWAY_DETAILS, SUMMIT_HISTORY_DETAILS, TOURNAMENT_DETAILS, TESTIMONIALS]

export {
    CONTACT, EVENTS, GIVEAWAY, HOME, PROFILE, STORY, GAME_DETAILS, GIVEAWAY_DETAILS, SUMMIT_HISTORY_DETAILS, TOURNAMENT_DETAILS, TESTIMONIALS
}    